language: python

python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7-dev" # Fails because libyaml fails to build

install:
  - "pip install -r requirements-ci.txt"

script:
  # ignore output from install
  - python setup.py install >> /dev/null
  - snekchek

cache: pip

notifications:
  email: false
