language: python

python:
  - "3.6"

install:
  - "pip install -r requirements-ci.txt"

script:
  - python setup.py install
  - snekchek
  - snekchek --json

cache: pip

notifications:
  email: false
